# ================================
# CONFIGURACIÓN GENERAL
# ================================
##spring.application.name=GestionProyectos
spring.application.name=gestion-proyectos
server.port=8080

# ================================
# BASE DE DATOS H2 (embebida)
# ================================
spring.datasource.url=jdbc:h2:file:./data/gestionproyectos-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
