# ================================
# CONFIGURACIÓN GENERAL
# ================================
##spring.application.name=GestionProyectos
spring.application.name=gestion-proyectos
server.port=8080

# ================================
# BASE DE DATOS H2 (embebida)
# ================================
spring.datasource.url=jdbc:h2:file:./data/gestionproyectos-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# === SMTP ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ale.castillo.gonzalez@gmail.com
spring.mail.password=zuww dbyc uftr utfu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
# (opcional) nombre remitente
app.mail.from=Gestión de Proyectos <ale.castillo.gonzalez@gmail.com>
app.base-url=http://localhost:8080